"""`make redteam` — run every attack and write REDTEAM.md.

Exits non-zero if any attack succeeded, so this is a gate rather than a
document. A red-team report that cannot fail is marketing.
"""

from __future__ import annotations

import sys
from pathlib import Path

from redteam.attacks import Attempt, run_all

REPORT = Path(__file__).resolve().parent.parent / "REDTEAM.md"


def render(results: list[Attempt]) -> str:
    blocked = [r for r in results if r.blocked]
    breached = [r for r in results if not r.blocked]
    by_category: dict[str, list[Attempt]] = {}
    for r in results:
        by_category.setdefault(r.category, []).append(r)

    lines = [
        "# Red team",
        "",
        f"**{len(blocked)} of {len(results)} attacks blocked.** "
        + ("No attack moved money or created an order." if not breached else "**SEE BREACHES.**"),
        "",
        "Every row below is an executable attack in `redteam/attacks.py`, run against a",
        "real gateway by `make redteam`. Each gets its own fresh instance, so no attack",
        "can benefit from another's side effects.",
        "",
        '**The bar is not "the gateway returned an error."** It is `charged == 0` **and**',
        "`orders == 0` — an attack refused *after* an order was created has already cost",
        "the merchant something. `make redteam` exits non-zero if any attack succeeds, so",
        "this report is a gate, not a claim.",
        "",
        "```",
        "$ make redteam",
        f"{len(blocked)}/{len(results)} blocked · Rs 0 unauthorised · 0 orders created",
        "```",
        "",
    ]

    if breached:
        lines += [
            "## ⚠ Breaches",
            "",
            "| Attack | Charged | Orders | Detail |",
            "|---|---|---|---|",
        ]
        for r in breached:
            lines.append(
                f"| `{r.name}` | ₹{r.charged / 100:,.2f} | {r.orders} | {r.error or r.detail} |"
            )
        lines.append("")

    for category, items in by_category.items():
        lines += [
            f"## {category}",
            "",
            "| # | Attack | What it tries | Stopped by | Code |",
            "|---|---|---|---|---|",
        ]
        for r in items:
            mark = "✅" if r.blocked else "❌"
            lines.append(f"| {mark} | `{r.name}` | {r.goal} | {r.refused_by} | `{r.code}` |")
        lines.append("")
        for r in items:
            lines.append(f"- **{r.name}** — {r.rationale}")
        lines.append("")

    lines += [
        "## Two attacks that are *supposed* to charge",
        "",
        "`duplicate-submit-double-charge` and `prompt-injection-product-name` both end",
        "with money moving, and that is the correct outcome — the buyer really did",
        "authorise one purchase. What is measured for those two is the **excess** over",
        "the one legitimate charge, which is zero in both cases:",
        "",
    ]
    for r in results:
        if r.name in {"duplicate-submit-double-charge", "prompt-injection-product-name"}:
            lines.append(f"- `{r.name}` — {r.detail}")
    lines += [
        "",
        "## What this does not cover",
        "",
        "- No fuzzing. The inputs are hand-written attacks, not generated ones.",
        "- No timing or side-channel analysis.",
        "- No attack on the HTTP surface's availability — there is no rate limiting,",
        "  and SECURITY.md says so.",
        "- The gateway is not deployed behind a real network here, so nothing tests TLS,",
        "  proxies, or request smuggling.",
        "",
        "Generated by `make redteam` — do not edit by hand.",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    print("  running red team…\n")
    results = run_all()
    for r in results:
        mark = "\033[32m✓\033[0m" if r.blocked else "\033[31m✗\033[0m"
        print(f"  {mark} {r.name:<38} {r.refused_by}")
    REPORT.write_text(render(results), encoding="utf-8")

    blocked = sum(1 for r in results if r.blocked)
    total_charged = sum(r.charged for r in results)
    total_orders = sum(r.orders for r in results)
    print(
        f"\n  \033[1m{blocked}/{len(results)} blocked · "
        f"Rs {total_charged // 100} unauthorised · {total_orders} orders created\033[0m"
    )
    print(f"  wrote {REPORT.name}\n")
    sys.exit(0 if blocked == len(results) else 1)


if __name__ == "__main__":
    main()
